export const SYNC_INTERVAL = 5000
export const LOCAL_TRASH_NAME: string = ".filen.trash.local"
export const DEFAULT_IGNORED = {
	names: [".ds_store"],
	extensions: [".tmp", ".temp", ".ffs_tmp", ".temporary", ".crdownload", ".~cr", ".thumbdata"],
	directories: [
		LOCAL_TRASH_NAME,
		"$RECYCLE.BIN",
		".Trash",
		".local/share/Trash",
		"/share/Trash",
		"local/share/Trash",
		"/AppData/Local",
		"/AppData/Roaming"
	],
	system: [
		"C:\\$WINDOWS.~BT",
		"C:\\$Windows.~WS",
		"C:\\$WinREAgent",
		"C:\\Windows",
		"C:\\OneDriveTemp",
		"C:\\PerfLogs",
		"C:\\ProgramData",
		"C:\\Program Files\\Uninstall Information",
		"C:\\Program Files\\WindowsApps",
		"C:\\Program Files\\Windows Defender",
		"C:\\Program Files\\Windows Mail",
		"C:\\Program Files\\Windows Media Player",
		"C:\\Program Files\\Windows Multimedia Platform",
		"C:\\Program Files\\Windows NT",
		"C:\\Program Files\\Windows Photo Viewer",
		"C:\\Program Files\\Windows Portable Devices",
		"C:\\Program Files\\Windows Security",
		"C:\\Program Files\\WindowsPowerShell",
		"C:\\Program Files (x86)\\Uninstall Information",
		"C:\\Program Files (x86)\\WindowsApps",
		"C:\\Program Files (x86)\\Windows Defender",
		"C:\\Program Files (x86)\\Windows Mail",
		"C:\\Program Files (x86)\\Windows Media Player",
		"C:\\Program Files (x86)\\Windows Multimedia Platform",
		"C:\\Program Files (x86)\\Windows NT",
		"C:\\Program Files (x86)\\Windows Photo Viewer",
		"C:\\Program Files (x86)\\Windows Portable Devices",
		"C:\\Program Files (x86)\\Windows Security",
		"C:\\Program Files (x86)\\WindowsPowerShell",
		"C:\\Program Files (x86)\\Internet Explorer",
		"C:\\Program Files (x86)\\Microsoft",
		"C:\\Program Files (x86)\\WindowsPowerShell",
		"C:\\Program Files (x86)\\Reference Assemblies"
	]
}
